In [1]:
import numpy as np

In [2]:
x = np.array( [1, 2, 3, 4, 5] )
x

array([1, 2, 3, 4, 5])

In [3]:
x.dtype

dtype('int64')

In [4]:
y = np.array( [1.0, 2, 3, 4, 5] )
y.dtype

dtype('float64')

In [5]:
len(x)

5

In [6]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(1, 3, 0.5)

array([1. , 1.5, 2. , 2.5])

In [8]:
v = np.zeros(5)
v

array([0., 0., 0., 0., 0.])

In [9]:
np.ones(4)

array([1., 1., 1., 1.])